name = "FighterJets"
uuid = "1f7dde27-6782-4df0-9908-f5b96187ac71"
authors = ["Francososa <franky.sosa@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
